packages:
  - "examples/*"
  - "examples/module/playground"
  - "stubs/*"

shellEmulator: true

onlyBuiltDependencies:
  - better-sqlite3
  - '@tailwindcss/oxide'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - unrs-resolver
  - vue-demi

