packages:
  - examples/*
  - examples/module/playground
  - stubs/*

overrides:
  '@cucumber/cucumber': 12.9.0
  '@nuxt/schema': 4.4.8
  '@nuxt/test-utils': workspace:*
  '@types/node': 24.13.2
  rollup: 4.62.2
  vite: 8.0.16
  vite-node: 6.0.0
  vitest: 4.1.9
  vue: ^3.5.38

patchedDependencies:
  node-mock-http: patches/node-mock-http.patch

shellEmulator: true

ignoreWorkspaceRootCheck: true

allowBuilds:
  "@parcel/watcher": false
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: false
  oxc-resolver: false
  unrs-resolver: false
  vue-demi: false
