name: release

on:
  push:
    tags:
      - v*

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  release:
    concurrency:
      group: release
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24.9.0
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Update npm for trusted publishing
        run: npm install -g npm@11.6.0

      - run: pnpm config set registry https://registry.npmjs.org
      - run: npm config set registry https://registry.npmjs.org

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Prepare build environment
        run: pnpm dev:prepare

      - name: 📦 Release
        run: npm publish --access public
